# src/bot/terms.py
"""Terms of Use text for the Düsseldorf Termin Checker bot."""

TERMS = {
    "en": (
        "📋 *Terms of Use — Düsseldorf Termin Checker*\n\n"
        "*What this bot does*\n"
        "This bot monitors the public appointment system of the City of Düsseldorf (TEVIS) "
        "and sends you notifications when appointment slots become available.\n\n"
        "*No guarantees*\n"
        "Appointment availability depends entirely on third-party systems outside our control. "
        "We do not guarantee that any slots will be found, that notifications will be delivered "
        "on time, or that the service will be available without interruption. The bot may stop "
        "working at any time due to changes in the TEVIS system or other technical issues.\n\n"
        "*Premium / voluntary support*\n"
        "Premium features are enabled as a thank-you for voluntary financial support of the "
        "developer. This is not a purchase of a service or a subscription in the legal sense. "
        "No refunds are provided, as any contribution is entirely voluntary.\n\n"
        "*Your data*\n"
        "We store your Telegram user ID and subscription preferences solely to operate this "
        "service. No personal data is shared with third parties. You can have your data deleted "
        "at any time by cancelling all subscriptions and contacting the developer via this bot.\n\n"
        "*Limitation of liability*\n"
        "The developer is not liable for any missed appointments, damages, losses, or other "
        "consequences arising from the use or unavailability of this bot.\n\n"
        "*Changes*\n"
        "These terms may be updated at any time. Continued use of the bot after changes "
        "constitutes acceptance of the updated terms.\n\n"
        "*Contact*\n"
        "For questions or data deletion requests, please contact the developer via this Telegram bot."
    ),
    "de": (
        "📋 *Nutzungsbedingungen — Düsseldorf Termin Checker*\n\n"
        "*Was dieser Bot tut*\n"
        "Dieser Bot überwacht das öffentliche Terminsystem der Stadt Düsseldorf (TEVIS) und "
        "benachrichtigt Sie, wenn Terminslots verfügbar werden.\n\n"
        "*Keine Garantien*\n"
        "Die Terminverfügbarkeit hängt vollständig von Systemen Dritter ab, auf die wir keinen "
        "Einfluss haben. Wir garantieren nicht, dass Termine gefunden werden, dass "
        "Benachrichtigungen rechtzeitig zugestellt werden oder dass der Dienst ohne "
        "Unterbrechung verfügbar ist. Der Bot kann jederzeit aufhören zu funktionieren, "
        "z. B. aufgrund von Änderungen am TEVIS-System oder anderer technischer Probleme.\n\n"
        "*Premium / freiwillige Unterstützung*\n"
        "Premium-Funktionen werden als Dankeschön für die freiwillige finanzielle Unterstützung "
        "des Entwicklers freigeschaltet. Dies stellt keinen Kauf einer Dienstleistung oder ein "
        "Abonnement im Rechtssinne dar. Eine Rückerstattung wird nicht gewährt, da jeder Beitrag "
        "vollständig freiwillig ist.\n\n"
        "*Ihre Daten*\n"
        "Wir speichern Ihre Telegram-Nutzer-ID und Abonnement-Einstellungen ausschließlich zum "
        "Betrieb dieses Dienstes. Personenbezogene Daten werden nicht an Dritte weitergegeben. "
        "Sie können jederzeit die Löschung Ihrer Daten verlangen, indem Sie alle Abonnements "
        "kündigen und den Entwickler über diesen Bot kontaktieren.\n\n"
        "*Haftungsbeschränkung*\n"
        "Der Entwickler haftet nicht für verpasste Termine, Schäden, Verluste oder sonstige "
        "Folgen, die aus der Nutzung oder Nichtverfügbarkeit dieses Bots entstehen.\n\n"
        "*Änderungen*\n"
        "Diese Nutzungsbedingungen können jederzeit aktualisiert werden. Die weitere Nutzung "
        "des Bots nach Änderungen gilt als Zustimmung zu den aktualisierten Bedingungen.\n\n"
        "*Kontakt*\n"
        "Für Fragen oder Anfragen zur Datenlöschung wenden Sie sich bitte über diesen "
        "Telegram-Bot an den Entwickler."
    ),
}
